### PR TITLE
Add util script to run `npm install` in all bundles

### PR DESCRIPTION
**Pull request by seanohue**
This is good for when (for any reason), your npm dependencies get blown up in the submodules.

### CODE REVIEW

**Comment by digitalsadhu** [comment]
Should there be a matching run script for this in package.json?

**Comment by seanohue** [comment]
Good idea @digitalsadhu -- added it.

**Comment by shawncplus** [comment]
I don't think this is necessary since you can just run `git submodule foreach npm install`

**Comment by shawncplus** [comment]
@seanohue I had to update package.json to fix the missing preinstall for `link-module-alias` so you'll have to update your package.json.

**Comment by seanohue** [comment]
TIL that `git submodule foreach` is a thing. Also, the missing preinstall was probably the root cause of the issue that made me have to create this command. I may just change the `npm` script to do `git submodule foreach npm install` and then get rid of the JS file.

**Pull request closed without merging**
