### PR TITLE
WIP: Move CommandParser out of core

### PR DESCRIPTION
**Pull request by nahilep**
This is not final, I need to discuss something first.

I have `const CommandType = require('../bundles/ranvier-lib/lib/CommandType');` in src/Command.js to make it run. Obviously this is a no-go. How would I approach this the best way?

Also removed unused requires in files touched.

### CODE REVIEW

**Comment by shawncplus** [comment]
The only suggestion I would have right now is to keep `CommandType` in the core, I'll have to think about it some more if it's possible to move that out or if commands should even have a type. The way the bundles use `CommandType` is a bit strange

**Comment by nahilep** [comment]
From what I can see `CommandType` is only used in `CommandParser` and in `src/Command.js` to set a default value for `command.type` in `constructor()` -> `this.type = def.type || CommandType.COMMAND;`

If we could get rid of this default assignment we wouldn't need it in `src/`.

**Comment by shawncplus** [comment]
That's definitely the case but I worry that would break things if we just removed the default. I'll have to look into it more after work

**Comment by shawncplus** [comment]
Closing this as this has been implemented in core

**Pull request closed without merging**
